version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          repo: AWS_RESOURCE_NAME_PREFIX
          region: AWS_DEFAULT_REGION
          tag: CIRCLE_SHA1
